version: "3.8"

services:

  server:
    build: ./server/
    volumes:
      - ./server/data/teamcity_server/datadir:/data/teamcity_server/datadir
      - ./server/logs:/opt/teamcity/logs
    ports:
      - 80:8111

  agent-android:
    platform: linux/amd64
    build:
      context: ./agent/
      args:
        JDK_VERSION: 11
        JDK_URL: https://corretto.aws/downloads/resources/11.0.22.7.1/amazon-corretto-11.0.22.7.1-linux-x64.tar.gz
        JDK_SHA256SUM: f512bedb85adbef31c3823e219d9369e2bccb650575615478619b499f8e21117
        ANDROID_CLT_URL: https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        ANDROID_PLATFORM_VERSION: 33
        ANDROID_BUILD_TOOLS_VERSION: 30.0.3
    environment:
      - SERVER_URL=server:8111
    depends_on:
      - server